name: build

on: [push]

jobs:
  job_on_push:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Check compilation
        uses: actions-rs/cargo@v1
        with:
          command: check

  precheck:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Version
        id: vars
        shell: bash
        run: |
          version=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -n1)
          echo ::set-output name=VERSION::$(echo "$version")

  publish:
    needs: [ precheck ]
    if: startsWith(github.ref, 'refs/tags/')
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            use-cross: false
            jreleaser_platform: linux-x86_64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            use-cross: true
            jreleaser_platform: linux-aarch_64
          - target: x86_64-apple-darwin
            os: macos-latest
            use-cross: false
            jreleaser_platform: osx-x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            use-cross: false
            jreleaser_platform: osx-aarch_64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            use-cross: false
            jreleaser_platform: windows-x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use-cross }}
          command: build
          args: --locked --release --target=${{ matrix.target }}

      - name: Assemble
        uses: jreleaser/release-action@v2
        with:
          version: early-access
          arguments: assemble
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PLATFORM_OVERRIDE: ${{ matrix.jreleaser_platform }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: artifacts
          path: |
            out/jreleaser/assemble/reddsaver/archive/*.zip

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-output-${{ matrix.target }}
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties

  release:
    needs: [ precheck, publish ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Release
        uses: jreleaser/release-action@v2
        with:
          version: early-access
          arguments: full-release -PartifactsDir=artifacts -PskipArchiveResolver
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: output-release-logs
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
